# https://help.github.com/articles/customizing-css-and-html-in-your-jekyll-theme/

theme: jekyll-theme-cayman

# https://github.com/pages-themes/cayman/blob/master/_layouts/default.html
title: Development of a Numerical Library based on Hierarchical Domain Decomposition for Post Petascale Simulation

github:
  is_project_page: false
